name: Deploy site files

on:
    push:
        branches:
            - master # 只在 master 上 push 触发部署
        paths-ignore: # 下列文件的变更不触发部署，可以自行添加
            - README.md
            - LICENSE

jobs:
    deploy:
        runs-on: ubuntu-latest # 使用 ubuntu 系统镜像运行自动化脚本

        steps: # 自动化步骤
            -   uses: actions/checkout@v2 # 第一步，下载代码仓库
            -   name: Deploy to Server # 第二步，rsync 推文件
                uses: AEnterprise/rsync-deploy@v1.0 # 使用别人包装好的步骤镜像
                env:
                    DEPLOY_KEY: ${{ secrets.SERVER_SSH_KEY }} # 引用配置，SSH 私钥
                    ARGS: -avz --delete --exclude='*.pyc' # rsync 参数，排除.pyc 文件
                    SERVER_PORT: "22" # SSH 端口
                    FOLDER: ./ # 要推送的文件夹，路径相对于代码仓库的根目录
                    SERVER_IP: ${{ secrets.SSH_HOST }} # 引用配置，服务器的 host 名（IP 或者域名 domain.com）
                    USERNAME: ${{ secrets.SSH_USERNAME }} # 引用配置，服务器登录名
                    SERVER_DESTINATION: "/root/qq_bot/" # 部署到目标文件夹
            -   name: Restart server # 第三步，重启服务
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.SSH_HOST }} # 下面三个配置与上一步类似
                    username: ${{ secrets.SSH_USERNAME }}
                    key: ${{ secrets.SERVER_SSH_KEY }}
                    # 重启的脚本，根据自身情况做相应改动，一般要做的是 migrate 数据库以及重启服务器
                    script: |
                        cp /var/www/abyss/EfficientNet_0.82.pth /root/qq_bot/src/plugins/imageRecognition
                        cp /var/www/abyss/pytorch_model.bin /root/qq_bot/GPT2-chitchat/dialogue_model_path
                        supervisorctl restart qqbot
