name: Deploy site files

on:
    push:
        branches:
            - master # 只在 master 上 push 触发部署
        paths-ignore: # 下列文件的变更不触发部署，可以自行添加
            - README.md
            - LICENSE

jobs:
    deploy:
        runs-on: ubuntu-latest # 使用 ubuntu 系统镜像运行自动化脚本

        steps: # 自动化步骤
            -   uses: actions/checkout@v2 # 第一步，下载代码仓库

            -   name: copy file via ssh password
                uses: appleboy/scp-action@master
                with:
                    host: "139.180.198.39.ipssh.net"
                    username: "root"
                    key: ${{ secrets.SERVER_SSH_KEY }}
                    port: "22"
                    source: "bot.py,src/*"
                    target: "/root/qqbot"
            -   name: Restart server # 第三步，重启服务
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.SSH_HOST }} # 下面三个配置与上一步类似
                    username: ${{ secrets.SSH_USERNAME }}
                    key: ${{ secrets.SERVER_SSH_KEY }}
                    # 重启的脚本，根据自身情况做相应改动，一般要做的是 migrate 数据库以及重启服务器
                    script: |
                        supervisorctl restart qqbot
